//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mvc_5_Empty_Template1
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_orders
    {
        public int orderId { get; set; }
        public int userId { get; set; }
        public System.DateTime deliveredDate { get; set; }
        public int countPZ { get; set; }
    }
}
